// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUAQMFN3QSeATYcHeiLncrTOgH-KTdrzI',
    appId: '1:628145245789:web:be3ca503241e4232c8c7b4',
    messagingSenderId: '628145245789',
    projectId: 'pdd-plant',
    authDomain: 'pdd-plant.firebaseapp.com',
    storageBucket: 'pdd-plant.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAylFGn67AJDtSCygdZY1o5m4luaI0Qru4',
    appId: '1:628145245789:android:7fcdc640934b9d63c8c7b4',
    messagingSenderId: '628145245789',
    projectId: 'pdd-plant',
    storageBucket: 'pdd-plant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9gof8AfTKqLJaUxlYOyzyj_iPYIQhj2A',
    appId: '1:628145245789:ios:39191538290c5a7dc8c7b4',
    messagingSenderId: '628145245789',
    projectId: 'pdd-plant',
    storageBucket: 'pdd-plant.appspot.com',
    iosClientId: '628145245789-heuugttgv33rtph179gc42u1c21imi41.apps.googleusercontent.com',
    iosBundleId: 'com.macmads.plant',
  );
}
